# Generated by Django 5.1.5 on 2025-01-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_lesson_order_and_more'),
        ('courses', '0003_handle existing lessons'),
    ]

    operations = [
    ]
